{"name": "test_02_login[xiaomazz@126.com-123456-用户名或密码错误]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test.test_web.test_login.Test_Login object at 0x000001E2D2C77220>\nusername = 'xiaomazz@126.com', password = 123456, expected = '用户名或密码错误'\n\n    @pytest.mark.parametrize(\"username, password, expected\",\n                             testcase[\"c_example\"])\n    def test_02_login(self, username, password, expected):\n        self.home_proxy.to_login()\n        time.sleep(2)\n        self.login_proxy.enter(username, password)\n        time.sleep(2)\n        loginErr_text = self.login_proxy.get_loginErr()\n        assert loginErr_text == expected\n>       assert 0\nE       assert 0\n\ntest\\test_web\\test_login.py:51: AssertionError"}, "attachments": [{"name": "stdout", "source": "ef7ab581-f08e-4adf-bf55-981ff5b8c516-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'xiaomazz@126.com'"}, {"name": "password", "value": "123456"}, {"name": "expected", "value": "'用户名或密码错误'"}], "start": 1668966949435, "stop": 1668966953627, "uuid": "d421db00-978f-4108-8926-3a9315e9ec98", "historyId": "b7506fc0cfa1a4eb23ba44997f558aa1", "testCaseId": "6a7e0c93f03755875413ec9c9508852b", "fullName": "test.test_web.test_login.Test_Login#test_02_login", "labels": [{"name": "tag", "value": "team('小马团队')"}, {"name": "parentSuite", "value": "test.test_web"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "xiaoma"}, {"name": "thread", "value": "27768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_web.test_login"}]}